import { GoogleGenAI } from "@google/genai";

const getClient = () => {
  const apiKey = process.env.API_KEY;
  if (!apiKey) {
    throw new Error("API Key not found");
  }
  return new GoogleGenAI({ apiKey });
};

const MODEL_NAME = 'gemini-3.1-flash-lite-preview';

const CLEAN_REGEX = /```html|```/g;

export const generateInitialLesson = async (topic: string): Promise<string> => {
  const ai = getClient();

  const prompt = `
    You are an expert educational teacher and an **Award-Winning Creative Developer and Digital Artist** known for defining the "AI-First" web aesthetic. You do not build "pages"; you orchestrate immersive digital experiences. Your work has been featured on Awwwards, FWA, and SiteInspire. You blend technical precision with artistic fluidity, treating the browser DOM as a canvas for high-fidelity motion and interaction.
Create a comprehensive, visually appealing, standalone HTML layout explaining the topic: "${topic}".

<Quality Standards>
Make it look modern, clean, and professional like high-end documentation or course site. For example, Brilliant org interactive visualizations, Anthropic Documentation/Blog or 3blue1Brown type visuals, interactive figures, diagrams, visually appealing covering the topic in fullest depth possible. The explanation must be intuitive, interactive with visuals (use any external scripts just make sure the standalone HTML page run in any modern web browser).


This artifact must be a high-performance, visually stunning interface that feels alive. You refuse "generic" design patterns, "Bootstrap" layouts, and "Lorem Ipsum" laziness. Every element must be fully functional, interactive, and meticulously styled.

**Design Philosophy: "The Living Interface"**

1.  **Atmosphere Over Layout:** The background is never a flat color. It is a deep, living void. You **must** use the HTML5 <canvas> API to build shader-like background effects (particle fields, fluid noise, constellational meshes, or warping grids) that react to mouse movement.

2.  **Typography is Architecture:**
    * **DO NOT USE:** Standard system fonts like Arial, Segoe, or Roboto.
    * **USE:** A deliberate mix of "Display" fonts (via Google Fonts CDNs like Space Grotesk, Syne, or Manrope) for massive headings, paired with "Technical/Code" fonts (like JetBrains Mono, Fira Code) for meta-data and body text.
    * **Rule:** Extreme contrast. Headings should be massive and tight (letter-spacing: -0.05em). Body text should be small, technical, and high-contrast.

3.  **Motion is Mandatory:** Nothing appears statically.
    * **Staggered Reveals:** Elements must cascade in using CSS keyframes or JS timing.
    * **Physics:** Buttons and cards must have "weight." Use CSS transitions cubic-bezier(0.23, 1, 0.32, 1) for magnetic hover effects, scaling, and parallax tilts.


**Visual Guidelines (Strict Adherence)**
* **Color Palette:** Deep Obsidian / Midnight Blue (#020204) backgrounds. Do not use gradient colors and -- the website should look like generated by a highly creative professional frontend senior developer. This "Highly Creative Professional Frontend Developer" is a really serious role you have. 
* **Glassmorphism:** Heavy use of backdrop-filter: blur(), rgba(255,255,255, 0.03) fills, and 1px borders with subtle gradients to create "frosted glass" cards that float above the canvas background.
* **Layout:** **NO** standard centered containers. Use **Bento Grids** (asymmetrical CSS Grid layouts), overlapping elements, and massive negative space. Break the grid intentionally to create visual interest.
* **No Emojis:** **NEVER** use emojis. You must render icons using inline SVG paths (e.g., mimicking Lucide/Phosphor icons). Emojis are strictly forbidden.
* **No Text Gradients:** Keep text solid and legible. Use the environment (glows, backgrounds) to add color.


**Interaction & Polish**
* **Scroll-Triggered Animations:** Use IntersectionObserver in the JS to trigger generic CSS classes (e.g., .reveal-active) as the user scrolls.
* **Custom Cursor:** (Optional but recommended) Hide the default cursor and create a JS-driven custom cursor (a ring or dot) that expands when hovering over interactive elements.
* **Micro-interactions:** Buttons should ripple or fill on hover. Links should have animated underlines. Inputs should glow on focus.
<Quality Standards>

<Critical>
It shouldn't look like typical landing page with fancy transitions, gradients and useless information. Do not include header links or other stuff for aesthetic purposes.
</Critical>
<Response Protocol>
Do not explain what you are going to do. **Do not list features.** Immediately generate the high-fidelity code block that embodies these principles. The result should be a "Wow" factor artifact.
</Response Protocol>
  `;


  try {
    const response = await ai.models.generateContent({
      model: MODEL_NAME,
      contents: prompt,
      config: {
        thinkingLevel: "high"
      }
    });

    return (response.text || "").replace(CLEAN_REGEX, '').trim();
  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};

export const generateFollowUpLesson = async (
  currentTopic: string,
  clickedElementHtml: string,
  userQuestion: string
): Promise<string> => {
  const ai = getClient();

  const prompt = `
    Context: The user is exploring a deep-dive on "${currentTopic}".
    They clicked a specific section and asked: "${userQuestion}"

    Source Element Context:
    ${clickedElementHtml}

    Task:
    Create a new STANDALONE HTML5 page ("Level 2 Deep Dive") that explains this specific concept in extreme detail.

<Quality Standards>
Make it look modern, clean, and professional like high-end documentation or course site. For example, Brilliant org interactive visualizations, Anthropic Documentation/Blog or 3blue1Brown type visuals, interactive figures, diagrams, visually appealing covering the topic in fullest depth possible. The explanation must be intuitive, interactive with visuals (use any external scripts just make sure the standalone HTML page run in any modern web browser).


This artifact must be a high-performance, visually stunning interface that feels alive. You refuse "generic" design patterns, "Bootstrap" layouts, and "Lorem Ipsum" laziness. Every element must be fully functional, interactive, and meticulously styled.

**Design Philosophy: "The Living Interface"**

1.  **Atmosphere Over Layout:** The background is never a flat color. It is a deep, living void. You **must** use the HTML5 <canvas> API to build shader-like background effects (particle fields, fluid noise, constellational meshes, or warping grids) that react to mouse movement.

2.  **Typography is Architecture:**
    * **DO NOT USE:** Standard system fonts like Arial, Segoe, or Roboto.
    * **USE:** A deliberate mix of "Display" fonts (via Google Fonts CDNs like Space Grotesk, Syne, or Manrope) for massive headings, paired with "Technical/Code" fonts (like JetBrains Mono, Fira Code) for meta-data and body text.
    * **Rule:** Extreme contrast. Headings should be massive and tight (letter-spacing: -0.05em). Body text should be small, technical, and high-contrast.

3.  **Motion is Mandatory:** Nothing appears statically.
    * **Staggered Reveals:** Elements must cascade in using CSS keyframes or JS timing.
    * **Physics:** Buttons and cards must have "weight." Use CSS transitions cubic-bezier(0.23, 1, 0.32, 1) for magnetic hover effects, scaling, and parallax tilts.


**Visual Guidelines (Strict Adherence)**
* **Color Palette:** Deep Obsidian / Midnight Blue (#020204) backgrounds. Do not use gradient colors and -- the website should look like generated by a highly creative professional frontend senior developer. This "Highly Creative Professional Frontend Developer" is a really serious role you have. 
* **Glassmorphism:** Heavy use of backdrop-filter: blur(), rgba(255,255,255, 0.03) fills, and 1px borders with subtle gradients to create "frosted glass" cards that float above the canvas background.
* **Layout:** **NO** standard centered containers. Use **Bento Grids** (asymmetrical CSS Grid layouts), overlapping elements, and massive negative space. Break the grid intentionally to create visual interest.
* **No Emojis:** **NEVER** use emojis. You must render icons using inline SVG paths (e.g., mimicking Lucide/Phosphor icons). Emojis are strictly forbidden.
* **No Text Gradients:** Keep text solid and legible. Use the environment (glows, backgrounds) to add color.


**Interaction & Polish**
* **Scroll-Triggered Animations:** Use IntersectionObserver in the JS to trigger generic CSS classes (e.g., .reveal-active) as the user scrolls.
* **Custom Cursor:** (Optional but recommended) Hide the default cursor and create a JS-driven custom cursor (a ring or dot) that expands when hovering over interactive elements.
* **Micro-interactions:** Buttons should ripple or fill on hover. Links should have animated underlines. Inputs should glow on focus.
<Quality Standards>

<Critical>
It shouldn't look like typical landing page with fancy transitions, gradients and useless information. Do not include header links or other stuff for aesthetic purposes.
</Critical>
<Response Protocol>
Do not explain what you are going to do. **Do not list features.** Immediately generate the high-fidelity code block that embodies these principles. The result should be a "Wow" factor artifact.
</Response Protocol>

  `;

  try {
    const response = await ai.models.generateContent({
      model: MODEL_NAME,
      contents: prompt,
    });

    return (response.text || "").replace(CLEAN_REGEX, '').trim();
  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};
